const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const LS={get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function currentUser(){return LS.get('bigmart_current_user',null)}
function showToast(msg,error=false){const box=$('#toast');if(!box)return;const t=document.createElement('div');t.className='toast'+(error?' error':'');t.textContent=msg;box.appendChild(t);setTimeout(()=>t.remove(),2600)}
function money(n){return 'Rs. '+Number(n).toLocaleString('en-IN')}
function isWish(id){return LS.get('bigmart_wishlist',[]).includes(Number(id))}
function updateCounts(){const cart=LS.get('bigmart_cart',[]),wish=LS.get('bigmart_wishlist',[]);const c=$('#cartCount');const w=$('#wishCount');if(c)c.textContent=cart.reduce((a,x)=>a+x.qty,0);if(w)w.textContent=wish.length}
function addToCart(id,qty=1){id=Number(id);const p=PRODUCTS.find(x=>x.id===id);if(!p)return;let cart=LS.get('bigmart_cart',[]);const item=cart.find(x=>x.id===id);if(item)item.qty=Math.min(item.qty+qty,p.stock);else cart.push({id,qty:Math.min(qty,p.stock)});LS.set('bigmart_cart',cart);updateCounts();showToast(p.name+' added to cart')}
function toggleWish(id){id=Number(id);let w=LS.get('bigmart_wishlist',[]);w=w.includes(id)?w.filter(x=>x!==id):[...w,id];LS.set('bigmart_wishlist',w);updateCounts();renderAllWishButtons();showToast(w.includes(id)?'Added to wishlist':'Removed from wishlist')}
function renderAllWishButtons(){$$('.heart[data-id]').forEach(b=>{b.classList.toggle('active',isWish(b.dataset.id));b.textContent=isWish(b.dataset.id)?'♥':'♡'})}
function productCard(p){return `<article class="product-card"><div class="product-image"><span class="discount">-${p.discount}%</span><button class="heart ${isWish(p.id)?'active':''}" data-id="${p.id}" onclick="toggleWish(${p.id})">${isWish(p.id)?'♥':'♡'}</button><a href="product-details.html?id=${p.id}">${p.image}</a></div><div class="product-info"><span class="brand">${p.brand} · ${p.weight}</span><a href="product-details.html?id=${p.id}" class="product-name">${p.name}</a><div class="rating">★ ${p.rating} <span style="color:#8b9891">(${p.reviews})</span></div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.oldPrice)}</span></div><div class="add-row"><button class="btn primary" onclick="addToCart(${p.id})">🛒 Add to Cart</button></div></div></article>`}
function renderProducts(list,target){const el=$(target);if(!el)return;el.innerHTML=list.length?list.map(productCard).join(''):`<div class="empty" style="grid-column:1/-1"><h3>No products found</h3><p>Try a different search or filter.</p><a class="btn primary" href="products.html">View all products</a></div>`;renderAllWishButtons()}
function header(){const u=currentUser();return `<header class="site-header"><div class="topbar"><div class="container"><span>🚚 Free delivery on selected orders</span><span>Customer support · 10:00 AM–8:00 PM</span></div></div><div class="container header-main"><a class="logo" href="index.html">BIG<span>MART</span></a><div class="search" id="headerSearch"><input id="globalSearch" placeholder="Search groceries, brands & more"><button onclick="globalSearch()">⌕</button></div><div class="header-actions"><button class="icon-btn" onclick="toggleMobileSearch()">🔎</button><a class="icon-btn" href="wishlist.html">♡<span class="badge" id="wishCount">0</span></a><a class="icon-btn" href="cart.html">🛒<span class="badge" id="cartCount">0</span></a>${u?`<a class="icon-btn hide-tablet" href="profile.html">👤</a>`:`<a class="btn primary hide-tablet" href="login.html">Login</a>`}</div></div><nav class="nav"><div class="container"><a href="index.html">Home</a><a href="categories.html">Categories</a><a href="products.html?category=Grocery">Grocery</a><a href="products.html?category=Fruits%20%26%20Vegetables">Fruits & Vegetables</a><a href="products.html?category=Dairy%20%26%20Bakery">Dairy & Bakery</a><a href="products.html?category=Beverages">Beverages</a><a href="products.html?category=Snacks">Snacks</a><a href="products.html?category=Personal%20Care">Personal Care</a><a href="products.html?category=Household">Household</a><a href="offers.html">Offers</a></div></nav></header><div class="bottom-nav"><a href="index.html"><b>⌂</b>Home</a><a href="categories.html"><b>☰</b>Categories</a><a href="products.html"><b>⌕</b>Search</a><a href="cart.html"><b>🛒</b>Cart</a><a href="${u?'profile.html':'login.html'}"><b>👤</b>Account</a></div>`}
function footer(){return `<footer class="site-footer"><div class="container footer-main"><div><div class="logo">BIG<span>MART</span></div><p>Fresh products, better prices and convenient shopping for every home.</p></div><div><h4>Shop</h4><a href="products.html">All Products</a><a href="offers.html">Offers</a><a href="categories.html">Categories</a><a href="wishlist.html">Wishlist</a></div><div><h4>Support</h4><a href="help.html">Help Center</a><a href="contact.html">Contact</a><a href="return-policy.html">Return Policy</a><a href="orders.html">Track Order</a></div><div><h4>Company</h4><a href="about.html">About</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="settings.html">Settings</a></div></div><div class="container footer-bottom">© 2026 Big Mart. Frontend demo built with HTML, CSS & JavaScript only.</div></footer>`}
function globalSearch(){const q=$('#globalSearch')?.value.trim();if(q)location.href='products.html?q='+encodeURIComponent(q)}
function toggleMobileSearch(){$('#headerSearch')?.classList.toggle('mobile-open');$('#globalSearch')?.focus()}
function slideHero(dir){const s=$$('.hero-slide');if(!s.length)return;let i=[...s].findIndex(x=>x.classList.contains('active'));s[i].classList.remove('active');i=(i+dir+s.length)%s.length;s[i].classList.add('active')}
function initBase(){const h=$('#site-header');if(h)h.innerHTML=header();const f=$('#site-footer');if(f)f.innerHTML=footer();updateCounts();const gs=$('#globalSearch');if(gs)gs.addEventListener('keydown',e=>{if(e.key==='Enter')globalSearch()});const cf=$('#contactForm');if(cf)cf.addEventListener('submit',e=>{e.preventDefault();showToast('Message sent successfully!');cf.reset()});document.body.classList.toggle('dark',localStorage.getItem('bigmart_theme')==='dark')}
document.addEventListener('DOMContentLoaded',initBase);
